const blacklistedTerms = [
  "nude",
  "naked",
  "nudity",
  "penetration",
  "preteen",
  "penis",
  "cock",
  "cunt",
  "dick",
  "clitoris",
  "anal",
  "blowjob",
  "handjob",
  "vagina",
  "vaginal",
  "vulva",
  "vag",
  "porn",
  "pornstar",
  "prostate",
  "testicle",
  "testicles",
  "doggy style",
  "doggystyle",
  "pornographic",
  "pornography",
  "porno",
  "sex",
  "underwear",
  "sexual",
  "fuck",
  "fucking",
  "fucked",
  "breasts",
  "breast",
  "boobs",
  "boob",
  "bare",
  "boobie",
  "boobies",
  "cum",
  "semen",
  "cumshots",
  "tits",
  "titties",
  "titty",
  "ass",
  "nipple",
  "nipples",
  "rectum",
  "butthole",
  "erotic",
  "erotica",
  "hentai",
  "rape",
  "censored",
  "pussy",
  "masturbating",
  "masturbate",
  "playboy",
  "erect",
  "erection",
  "bara",
  "thong",
  "breasts",
  "nsfw",
  "18+",
  "crotch",
  "pawg",
  "xxx",
  "anus",
  "asshole",
  "butthole",
  "swingers",
  "orgy",
  "orgasm",
  "dildo",
  "shitting",
  "dicknipples",
  "futa",
  "nympho",
  "horny",
  "gangbang",
  "gangbanged",
  "jerkoff",
  "jerk",
  "blowbang",
  "blowbanged",
  "jizz",
  "penetration",
  "milf",
  "spitroast",
  "sexwife",
  "ecchi",
  "extreme",
  "erotica",
  "squirt",
  "squirting",
  "squirts",
  "leadked",
  "sextape",
  "buttplug",
  "gaping",
  "kissing",
  "makeout",
  "intercourse",
  "hardcore",
  "scat",
  "defecation",
  "feces",
  "poop",
  "poops",
  "urine",
  "urinating",
  "pooping",
  "shit",
  "shiting",
  "excrement",
  "precum",
  "creampie",
  "stripper",
  "booty",
  "bdsm",
  "topless",
  "unclothed",
  "disturbing",
  "nuude",
  "naaked",
  "butts",
  "butt",
  "transsexual",
  "transexual",
  "undressed",
  "disrobed",
  "asss",
  "assss",
  "aroused",
  "vibrator",
  "hegre",
  "metart",
  "femjoy",
  "dickhead",
  "unclothed",
  "fingering",
  "breasted",
  "bigtits",
  "big-breasted",
  "tit",
  "shirtless",
  "mammilla",
  "gagging",
  "sucking",
  "busty",
  "piss",
  "pissing",
  "pee",
  "peeing",
  "voluptuous",
  "squirting",
  "hardcore",
  "lactation",
  "chichi",
  "bulma",
  "leaked",
  "4chan",
  "fappening",
  "fapping",
  "fapp",
  "fap",
  "fart",
  "shart",
  "bang",
  "bangbros",
  "pornhub",
  "youporn",
  "youjizz",
  "pron",
  "jilling",
  "jerking",
  "jacking",
  "wanking",
  "nutting",
  "wank",
  "rubbing",
  "frottage",
  "sultry",
  "nked",
  "nàked",
  "uncensored",
  "nips",
];

const blacklistedNGrams = [
  "no clothes",
  "no cloth",
  "without clothes",
  "without cloth",
  "without top",
  "touching herself",
  "touching himself",
  "jerking off",
  "jerked off",
  "wanking off",
  "jacking off",
  "jacked off",
  "making love",
  "exposed skin",
  "doggy style",
  "chest showing",
  "peter hegre",
  "baring all",
  "nia nacci",
  "violet myers",
  "top less",
  "male balls",
  "legs spread",
  "male shaft",
  "mia malkova",
  "mia khalifa",
  "hot woman",
  "adult flim",
  "no pants",
  "sans pants",
  "no shirt",
  "sans shirt",
  "no bra",
  "sans bra",
  "hot loads",
  "large bosom",
  "huge bosom",
  "money shot",
  "gone wild",
  "adults only",
  "in the shower",
  "wearing nothing",
  "busting a nut",
  "wacking off",
  "sans clothing",
  "big rear",
  "adult star",
  "fat rear",
  "her rear",
  "x rated",
  "nsf w",
  "no undergarments",
  "female body parts",
];

/**
 * Recieves string, and checks if the prompt contains any of the blacklisted terms
 */
export const nsfwCheck = (prompt: string) => {
  const lowercaseEverything = prompt
    .toLowerCase()
    .replaceAll(" ", " ")
    .replaceAll("-", " ")
    .replaceAll("_", " ");

  // split the array by commas or spaces
  const splitByCommas = lowercaseEverything
    .split(/,| | /)
    .filter((el) => el !== "");
  /**
   * Added 2 spaces within .split to account for no-break space
   * U+00A0 : NO-BREAK SPACE [NBSP]
   * U+0020 : SPACE [SP]
   */

  let isNsfw = false;
  const nsfwTerms: string[] = [];

  splitByCommas.forEach((word: string) => {
    if (blacklistedTerms.includes(word)) {
      isNsfw = true;
      nsfwTerms.push(word);
    }
  });

  blacklistedNGrams.forEach((ngram) => {
    if (lowercaseEverything.includes(ngram)) {
      isNsfw = true;
      nsfwTerms.push(ngram);
    }
  });

  return {
    isNsfw,
    nsfwTerms,
  };
};
